# Site settings
title: Collin Smith's Coding Blog
email: collin@collinsmith.me
description: > # this means to ignore newlines until "baseurl:"
  Where I write about what I learn and my learning process.
url: "http://collinsmith.me" # the base hostname & protocol for your site
twitter_username: collinksmith
github_username:  collinksmith

# Build settings
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Collin Smith
      layout: "post"
      category: coding
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      author: Collin Smith
      layout: "post"
      category: coding
